name: Release ORE Pool Server Docker Image

on:
  push:
    branches:
    - master
  workflow_dispatch:

env:
  IMAGE_NAME: ore-pool-server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./server/Dockerfile
        push: false
        tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}
        outputs: type=docker,dest=/tmp/docker-image.tar

    - name: Upload Docker image as artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: /tmp/docker-image.tar

    - name: Generate image info
      run: |
        # echo "IMAGE_NAME=${{ env.IMAGE_NAME }}" > image-info.txt
        # echo "IMAGE_TAG=${{ github.sha }}" >> image-info.txt
        echo "IMAGE_NAME=${{ env.IMAGE_NAME }}" >> $GITHUB_OUTPUT
        echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_OUTPUT

    - name: Upload image info
      uses: actions/upload-artifact@v4
      with:
        name: image-info
        path: image-info.txt